# .github/actions-config.yml
# This file provides supplemental matrix strategies for GitHub Actions.

check:
  matrix:
    os: [ ubuntu-latest, windows-latest ]
    python-version: [ '3.9', '3.10' ]
build:
  matrix:
    os: [ ubuntu-latest ]
    target: [ x86_64, arm64 ]
