# .github/release-manifest.toml
# This is the single source of truth for the release workflow.

[trigger]
tag_pattern = "v*"

[release]
skip_approval = true
body_template = """
# Release {{tag}} for {{repo_name}}

## Changelog
{{changelog}}

## Key Assets
{{assets_links}}

## Contributors
{{contributors}}

---
_Release generated on: `{{release_date}}`_
"""
[release.changelog]
diff_method = ".."
previous_tag_strategy = "latest"
[release.contributors]
template = """
<a href="https://github.com/{{owner}}/{{repo_name}}/graphs/contributors">
  <img src="https://contrib.rocks/image?repo={{owner}}/{{repo_name}}" />
</a>
"""
[release.assets]
include = ["dist/*", "release_notes.md"]
exclude = ["debug_symbols.zip"]
[release.assets.associate]
assets_links = "release_notes.md"

[check]
run_script = ".github/release.d/python-check.sh"
runs-on = "ubuntu-latest"
[check.features.cache]
enable = true
path = "~/.cache/pip"
key_file = "pyproject.toml"

[build]
run_script = ".github/release.d/build-python.sh"
runs-on = "ubuntu-latest"
[build.features.cache]
enable = true
path = "~/.cache/pip"
key_file = "pyproject.toml"
