# This workflow builds the release assets (distributions and a compressed archive)
# It is triggered manually, allowing developers to build assets on demand before creating a release.

name: Build Release Assets

on:
  workflow_call:

jobs:
  build:
    name: Build and Package Release Assets
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install build dependencies
        run: python -m pip install build

      - name: List files in workspace for debugging
        run: ls -R

      - name: Build distributions
        run: python -m build
        working-directory: ./nob

      - name: Upload release assets artifact
        # This artifact can be downloaded by the main release workflow
        uses: actions/upload-artifact@v4
        with:
          name: release-assets
          path: nob/dist/
