jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python ${{ github.event.inputs.python-version }}
              uses: actions/setup-python@v3
              with:
                  python-version: ${{ github.event.inputs.python-version }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install pytest ruff
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - name: Lint with ruff
              run: |
                  ruff format .
                  ruff check . --unsafe-fixes --fix
name: Python package
"on":
    workflow_dispatch:
        inputs:
            python-version:
                description: "Python version to use"
                required: true
                default: "3.8"
