name: Release Publisher
on:
    workflow_dispatch:
        inputs:
            tag:
                description: "The tag to create the release for (e.g., v1.0.0)"
                required: true
            previous_tag:
                description: "The previous tag for changelog generation"
                required: true

permissions:
    contents: write
    id-token: write # Required for gh cli

jobs:
    release:
        name: Create Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5
              with:
                  fetch-depth: 0 # Required for changelog generation

            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version: "3.12"

            - name: Install Dependencies
              run: pip install toml

            - name: Run Release Script
              env:
                  # The GITHUB_TOKEN is automatically available to the workflow.
                  # gh cli will use it for authentication.
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  python .github/release.d/run_release.py \
                    --tag "${{ github.event.inputs.tag }}" \
                    --previous-tag "${{ github.event.inputs.previous_tag }}"
